//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSep.Dal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuditEvent()
        {
            this.CustomAuditEvents = new HashSet<CustomAuditEvent>();
            this.EntityAuditEvents = new HashSet<EntityAuditEvent>();
        }
    
        public int Id { get; set; }
        public string EventType { get; set; }
        public string DatabaseName { get; set; }
        public string TableName { get; set; }
        public Nullable<int> PrimaryKey { get; set; }
        public string CrudAction { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> IdChangedBy { get; set; }
        public string Username { get; set; }
        public Nullable<int> IdDealer { get; set; }
        public string DealerName { get; set; }
        public string IpAddress { get; set; }
        public string ObjectAfterChanges { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public string ValidationResults { get; set; }
        public Nullable<int> CrudResult { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public string UserAgent { get; set; }
        public string Browser { get; set; }
        public string BrowserVersion { get; set; }
        public string Environment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomAuditEvent> CustomAuditEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityAuditEvent> EntityAuditEvents { get; set; }
    }
}
